// apps/frontend/components/audit-log/details/constants.ts

// ─── Polish labels ───────────────────────────────────────────────────────────

export const actionLabels: Record<string, string> = {
  CREATE: 'Utworzenie',
  UPDATE: 'Aktualizacja',
  DELETE: 'Usunięcie',
  SOFT_DELETE: 'Usunięcie (miękkie)',
  TOGGLE: 'Przełączenie',
  TOGGLE_ACTIVE: 'Przełączenie aktywności',
  REORDER: 'Zmiana kolejności',
  DUPLICATE: 'Duplikacja',
  STATUS_CHANGE: 'Zmiana statusu',
  CANCEL: 'Anulowanie',
  ARCHIVE: 'Archiwizacja',
  UNARCHIVE: 'Przywrócenie',
  RESTORE: 'Przywrócenie',
  AUTO_ARCHIVED: 'Auto-archiwizacja',
  AUTO_CONFIRM: 'Auto-potwierdzenie',
  MENU_UPDATE: 'Aktualizacja menu',
  MENU_UPDATED: 'Aktualizacja menu',
  MENU_REMOVE: 'Usunięcie menu',
  MENU_REMOVED: 'Usunięcie menu',
  MENU_SELECTED: 'Wybór menu',
  MENU_RECALCULATED: 'Przeliczenie menu',
  MENU_DIRECT_REMOVED: 'Bezpośrednie usunięcie menu',
  CATEGORY_EXTRAS_UPDATED: 'Aktualizacja dodatkowo płatnych porcji',
  CATEGORY_EXTRAS_REMOVED: 'Usunięcie dodatkowo płatnych porcji',
  PAYMENT_UPDATE: 'Aktualizacja płatności',
  MARK_PAID: 'Oznaczenie jako opłacone',
  MARK_UNPAID: 'Oznaczenie jako nieopłacone',
  DEPOSIT_CREATED: 'Dodanie zaliczki',
  DEPOSIT_DELETED: 'Usunięcie zaliczki',
  DEPOSIT_PAID: 'Opłacenie zaliczki',
  DEPOSIT_CANCELLED: 'Anulowanie zaliczki',
  DISCOUNT_APPLIED: 'Naliczenie rabatu',
  DISCOUNT_REMOVED: 'Usunięcie rabatu',
  BULK_ASSIGN: 'Zbiorcze przypisanie',
  QUEUE_ADD: 'Dodanie do kolejki',
  QUEUE_UPDATE: 'Aktualizacja w kolejce',
  QUEUE_REMOVE: 'Usunięcie z kolejki',
  QUEUE_SWAP: 'Zamiana pozycji',
  QUEUE_MOVE: 'Przeniesienie w kolejce',
  QUEUE_REORDER: 'Zmiana kolejności',
  QUEUE_REBUILD: 'Przebudowa kolejki',
  QUEUE_PROMOTE: 'Awans z kolejki',
  QUEUE_AUTO_CANCEL: 'Auto-anulowanie z kolejki',
  ATTACHMENT_UPLOAD: 'Wgranie załącznika',
  ATTACHMENT_ADD: 'Dodanie załącznika',
  ATTACHMENT_UPDATE: 'Aktualizacja załącznika',
  ATTACHMENT_ARCHIVE: 'Archiwizacja załącznika',
  ATTACHMENT_DELETE: 'Usunięcie załącznika',
  ATTACHMENT_DEDUP: 'Deduplikacja załącznika',
  LOGIN: 'Logowanie',
  LOGOUT: 'Wylogowanie',
  NOTE_UPDATED: 'Aktualizacja notatki',
};

export const actionColors: Record<string, string> = {
  ARCHIVE: 'bg-orange-100 text-orange-700 border-orange-200 dark:bg-orange-900/30 dark:text-orange-300 dark:border-orange-800',
  UNARCHIVE: 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-300 dark:border-emerald-800',
  RESTORE: 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-300 dark:border-emerald-800',
  CREATE: 'bg-blue-100 text-blue-700 border-blue-200 dark:bg-blue-900/30 dark:text-blue-300 dark:border-blue-800',
  UPDATE: 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/30 dark:text-amber-300 dark:border-amber-800',
  DELETE: 'bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-300 dark:border-red-800',
  SOFT_DELETE: 'bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-300 dark:border-red-800',
  STATUS_CHANGE: 'bg-violet-100 text-violet-700 border-violet-200 dark:bg-violet-900/30 dark:text-violet-300 dark:border-violet-800',
  CANCEL: 'bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-300 dark:border-red-800',
  LOGIN: 'bg-sky-100 text-sky-700 border-sky-200 dark:bg-sky-900/30 dark:text-sky-300 dark:border-sky-800',
  LOGOUT: 'bg-neutral-100 text-neutral-700 border-neutral-200 dark:bg-neutral-900/30 dark:text-neutral-300 dark:border-neutral-800',
  MARK_PAID: 'bg-green-100 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-300 dark:border-green-800',
  DISCOUNT_APPLIED: 'bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-900/30 dark:text-purple-300 dark:border-purple-800',
  DISCOUNT_REMOVED: 'bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-900/30 dark:text-purple-300 dark:border-purple-800',
  TOGGLE_ACTIVE: 'bg-teal-100 text-teal-700 border-teal-200 dark:bg-teal-900/30 dark:text-teal-300 dark:border-teal-800',
  DUPLICATE: 'bg-indigo-100 text-indigo-700 border-indigo-200 dark:bg-indigo-900/30 dark:text-indigo-300 dark:border-indigo-800',
};

export const entityLabels: Record<string, string> = {
  RESERVATION: 'Rezerwacja',
  RESERVATION_EXTRA: 'Usługa dodatkowa',
  CLIENT: 'Klient',
  CLIENT_CONTACT: 'Kontakt klienta',
  ROOM: 'Sala',
  HALL: 'Sala',
  MENU: 'Menu',
  USER: 'Użytkownik',
  DEPOSIT: 'Zaliczka',
  EVENT_TYPE: 'Typ wydarzenia',
  ATTACHMENT: 'Załącznik',
  QUEUE: 'Kolejka',
  DISH: 'Danie',
  MENU_TEMPLATE: 'Szablon menu',
  MENU_PACKAGE: 'Pakiet menu',
  PACKAGE: 'Pakiet',
  DOCUMENT_TEMPLATE: 'Szablon dokumentu',
  CATERING_ORDER: 'Zamówienie catering',
  SERVICE_CATEGORY: 'Kategoria usług',
  SERVICE_ITEM: 'Pozycja usługi',
  Role: 'Rola',
  CompanySettings: 'Ustawienia firmy',
  ServiceExtra: 'Usługa dodatkowa',
  ServiceCategory: 'Kategoria usług',
  ServiceItem: 'Pozycja usługi',
};

// ─── Field name translations (technical → Polish) ───────────────────────────

export const fieldLabels: Record<string, string> = {
  // Reservation fields
  status: 'Status',
  eventDate: 'Data wydarzenia',
  eventEndDate: 'Data zakończenia',
  startTime: 'Godzina rozpoczęcia',
  endTime: 'Godzina zakończenia',
  guestCount: 'Liczba gości',
  adultCount: 'Dorośli',
  childCount: 'Dzieci',
  adults: 'Dorośli',
  children: 'Dzieci',
  toddlers: 'Małe dzieci',
  guests: 'Liczba gości',
  oldGuests: 'Poprzednia liczba gości',
  newGuests: 'Nowa liczba gości',
  notes: 'Notatki',
  internalNotes: 'Notatki wewnętrzne',
  totalPrice: 'Cena całkowita',
  oldTotalPrice: 'Poprzednia cena całkowita',
  pricePerPerson: 'Cena za osobę',
  advanceAmount: 'Kwota zaliczki',
  isArchived: 'Zarchiwizowana',
  confirmedAt: 'Data potwierdzenia',
  cancelledAt: 'Data anulowania',
  archivedAt: 'Data archiwizacji',
  field: 'Pole',
  // Client fields
  firstName: 'Imię',
  lastName: 'Nazwisko',
  email: 'Email',
  phone: 'Telefon',
  clientType: 'Typ klienta',
  companyName: 'Nazwa firmy',
  nip: 'NIP',
  address: 'Adres',
  city: 'Miasto',
  postalCode: 'Kod pocztowy',
  country: 'Kraj',
  companyData: 'Dane firmy',
  contactData: 'Dane kontaktowe',
  newContact: 'Nowy kontakt',
  clientName: 'Nazwa klienta',
  // Menu fields
  name: 'Nazwa',
  description: 'Opis',
  price: 'Cena',
  basePrice: 'Cena bazowa',
  priceType: 'Typ ceny',
  isActive: 'Aktywny',
  packageName: 'Nazwa pakietu',
  templateName: 'Nazwa szablonu',
  packagePrice: 'Cena pakietu',
  optionsPrice: 'Cena opcji',
  totalMenuPrice: 'Cena menu łącznie',
  oldMenuPrice: 'Poprzednia cena menu',
  isNewSelection: 'Nowy wybór',
  // Relation / nested object fields
  hall: 'Sala',
  client: 'Klient',
  createdBy: 'Utworzony przez',
  eventType: 'Typ wydarzenia',
  menuSnapshot: 'Migawka menu',
  category: 'Kategoria',
  categoryId: 'ID kategorii',
  categoryName: 'Nazwa kategorii',
  packages: 'Pakiety',
  contacts: 'Osoby kontaktowe',
  items: 'Pozycje',
  serviceItem: 'Pozycja usługi',
  amenities: 'Udogodnienia',
  images: 'Zdjęcia',
  // Hall / Room fields
  capacity: 'Pojemność',
  isWholeVenue: 'Cały obiekt',
  allowWithWholeVenue: 'Dostępna z całym obiektem',
  allowMultipleBookings: 'Wielokrotne rezerwacje',
  // Deposit fields
  amount: 'Kwota',
  dueDate: 'Termin płatności',
  paidAt: 'Data opłaty',
  paymentMethod: 'Metoda płatności',
  amountPaid: 'Kwota zapłacona',
  wasPaid: 'Była opłacona',
  // Status change fields
  oldStatus: 'Poprzedni status',
  newStatus: 'Nowy status',
  // Discount fields
  discountType: 'Typ rabatu',
  discountValue: 'Wartość rabatu',
  discountAmount: 'Kwota rabatu',
  reason: 'Powód',
  restoredPrice: 'Przywrócona cena',
  discountBreakdown: 'Szczegóły rabatu',
  priceBreakdown: 'Szczegóły ceny',
  // Service / extras fields
  slug: 'Identyfikator',
  isExclusive: 'Wyłączny',
  extras: 'Usługi dodatkowe',
  removedCount: 'Liczba usuniętych',
  count: 'Liczba',
  replaced: 'Zastąpiono',
  newItem: 'Nowa pozycja',
  itemName: 'Nazwa pozycji',
  quantity: 'Ilość',
  portionTarget: 'Cel porcji',
  packageCategoryId: 'ID kategorii pakietu',
  // Queue fields
  position: 'Pozycja',
  queuePosition: 'Pozycja w kolejce',
  oldPosition: 'Poprzednia pozycja',
  newPosition: 'Nowa pozycja',
  queueDate: 'Data w kolejce',
  reservation1: 'Rezerwacja 1',
  reservation2: 'Rezerwacja 2',
  updatedCount: 'Liczba zaktualizowanych',
  positionChanges: 'Zmiany pozycji',
  cancelledCount: 'Liczba anulowanych',
  cancelledIds: 'Anulowane rezerwacje',
  triggeredBy: 'Wywołane przez',
  fromQueue: 'Z kolejki',
  toReservation: 'Do rezerwacji',
  dateCount: 'Liczba dat',
  dates: 'Daty',
  // Attachment fields
  filename: 'Nazwa pliku',
  fileSize: 'Rozmiar pliku',
  mimeType: 'Typ pliku',
  sizeBytes: 'Rozmiar (bajty)',
  originalSizeBytes: 'Oryginalny rozmiar',
  fileHash: 'Hash pliku',
  originalName: 'Oryginalna nazwa',
  attachmentId: 'ID załącznika',
  existingAttachmentId: 'ID istniejącego załącznika',
  label: 'Etykieta',
  compressed: 'Skompresowany',
  redirected: 'Przekierowany',
  // Event type fields
  eventTypeName: 'Nazwa typu wydarzenia',
  color: 'Kolor',
  standardHours: 'Standardowe godziny',
  extraHourRate: 'Stawka za dodatkową godzinę',
  // Menu package fields
  pricePerAdult: 'Cena za dorosłego',
  pricePerChild: 'Cena za dziecko',
  icon: 'Ikona',
  displayOrder: 'Kolejność wyświetlania',
  isPrimary: 'Kontakt główny',
  priceChanges: 'Zmiany cen',
  // Catering fields
  orderNumber: 'Numer zamówienia',
  deliveryType: 'Typ dostawy',
  guestsCount: 'Liczba gości',
  itemsCount: 'Liczba pozycji',
  extrasCount: 'Liczba dodatków',
  // Document template fields
  changeReason: 'Powód zmiany',
  // Common
  reservationId: 'ID rezerwacji',
  clientId: 'ID klienta',
  sourceId: 'ID źródła',
  orderedIds: 'Kolejność elementów',
  role: 'Stanowisko',
  menu: 'Menu',
  type: 'Typ',
  value: 'Wartość',
  data: 'Dane',
  oldValue: 'Poprzednia wartość',
  newValue: 'Nowa wartość',
};

// All known enum values → Polish translations
export const enumTranslations: Record<string, string> = {
  // Statuses
  PENDING: 'Oczekująca', CONFIRMED: 'Potwierdzona', CANCELLED: 'Anulowana',
  COMPLETED: 'Zakończona', DRAFT: 'Wersja robocza', TENTATIVE: 'Wstępna',
  PAID: 'Opłacona', UNPAID: 'Nieopłacona', PARTIAL: 'Częściowo opłacona',
  OVERDUE: 'Zaległa', ACTIVE: 'Aktywna', INACTIVE: 'Nieaktywna',
  ARCHIVED: 'Zarchiwizowana',
  // Payment methods
  CASH: 'Gotówka', BANK_TRANSFER: 'Przelew bankowy', BLIK: 'BLIK',
  CARD: 'Karta', ONLINE: 'Online', OTHER: 'Inne',
  // Client types
  INDIVIDUAL: 'Osoba prywatna', COMPANY: 'Firma',
  // Discount types
  PERCENTAGE: 'Procentowy', FIXED: 'Kwotowy',
  // Price types
  FLAT: 'Stała', PER_PERSON: 'Za osobę', PER_HOUR: 'Za godzinę',
  // Delivery types
  PICKUP: 'Odbiór własny', DELIVERY: 'Dostawa',
  // Portion targets
  ALL: 'Wszyscy', ADULTS_ONLY: 'Tylko dorośli', CHILDREN_ONLY: 'Tylko dzieci',
  // Boolean-like
  true: 'Tak', false: 'Nie',
};
