// apps/frontend/components/audit-log/timeline/timeline.constants.ts
// Extracted from EntityActivityTimeline.tsx — config objects for timeline display

// ─── Polskie labele akcji ───
export const actionLabels: Record<string, string> = {
  ARCHIVE: 'Archiwizacja',
  UNARCHIVE: 'Przywrócenie z archiwum',
  RESTORE: 'Przywrócenie',
  CREATE: 'Utworzenie',
  UPDATE: 'Aktualizacja',
  DELETE: 'Usunięcie',
  STATUS_CHANGE: 'Zmiana statusu',
  LOGIN: 'Logowanie',
  LOGOUT: 'Wylogowanie',
  QUEUE_ADD: 'Dodanie do kolejki',
  QUEUE_REMOVE: 'Usunięcie z kolejki',
  QUEUE_SWAP: 'Zamiana pozycji',
  QUEUE_MOVE: 'Przeniesienie',
  MARK_PAID: 'Oznaczenie płatności',
  ATTACHMENT_ADD: 'Dodanie załącznika',
  ATTACHMENT_DELETE: 'Usunięcie załącznika',
  MENU_RECALCULATED: 'Przeliczenie menu',
  MENU_CHANGE: 'Zmiana menu',
  DEPOSIT_ADD: 'Dodanie zaliczki',
  DEPOSIT_UPDATE: 'Aktualizacja zaliczki',
  DEPOSIT_DELETE: 'Usunięcie zaliczki',
  PRICE_CHANGE: 'Zmiana ceny',
  DISCOUNT_CHANGE: 'Zmiana rabatu',
}

export const actionColors: Record<string, string> = {
  ARCHIVE: 'bg-orange-100 text-orange-700 border-orange-200 dark:bg-orange-900/30 dark:text-orange-300 dark:border-orange-800',
  UNARCHIVE: 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-300 dark:border-emerald-800',
  RESTORE: 'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-300 dark:border-emerald-800',
  CREATE: 'bg-blue-100 text-blue-700 border-blue-200 dark:bg-blue-900/30 dark:text-blue-300 dark:border-blue-800',
  UPDATE: 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/30 dark:text-amber-300 dark:border-amber-800',
  DELETE: 'bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-300 dark:border-red-800',
  STATUS_CHANGE: 'bg-violet-100 text-violet-700 border-violet-200 dark:bg-violet-900/30 dark:text-violet-300 dark:border-violet-800',
  LOGIN: 'bg-sky-100 text-sky-700 border-sky-200 dark:bg-sky-900/30 dark:text-sky-300 dark:border-sky-800',
  LOGOUT: 'bg-neutral-100 text-neutral-700 border-neutral-200 dark:bg-neutral-900/30 dark:text-neutral-300 dark:border-neutral-800',
  QUEUE_ADD: 'bg-teal-100 text-teal-700 border-teal-200 dark:bg-teal-900/30 dark:text-teal-300 dark:border-teal-800',
  QUEUE_REMOVE: 'bg-rose-100 text-rose-700 border-rose-200 dark:bg-rose-900/30 dark:text-rose-300 dark:border-rose-800',
  QUEUE_SWAP: 'bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-900/30 dark:text-purple-300 dark:border-purple-800',
  QUEUE_MOVE: 'bg-indigo-100 text-indigo-700 border-indigo-200 dark:bg-indigo-900/30 dark:text-indigo-300 dark:border-indigo-800',
  MARK_PAID: 'bg-green-100 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-300 dark:border-green-800',
  ATTACHMENT_ADD: 'bg-cyan-100 text-cyan-700 border-cyan-200 dark:bg-cyan-900/30 dark:text-cyan-300 dark:border-cyan-800',
  ATTACHMENT_DELETE: 'bg-pink-100 text-pink-700 border-pink-200 dark:bg-pink-900/30 dark:text-pink-300 dark:border-pink-800',
  MENU_RECALCULATED: 'bg-lime-100 text-lime-700 border-lime-200 dark:bg-lime-900/30 dark:text-lime-300 dark:border-lime-800',
  MENU_CHANGE: 'bg-lime-100 text-lime-700 border-lime-200 dark:bg-lime-900/30 dark:text-lime-300 dark:border-lime-800',
  DEPOSIT_ADD: 'bg-green-100 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-300 dark:border-green-800',
  DEPOSIT_UPDATE: 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/30 dark:text-amber-300 dark:border-amber-800',
  DEPOSIT_DELETE: 'bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-300 dark:border-red-800',
  PRICE_CHANGE: 'bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-900/30 dark:text-amber-300 dark:border-amber-800',
  DISCOUNT_CHANGE: 'bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-900/30 dark:text-purple-300 dark:border-purple-800',
}

// Polskie nazwy pól
export const fieldLabels: Record<string, string> = {
  status: 'Status',
  firstName: 'Imię',
  lastName: 'Nazwisko',
  email: 'Email',
  phone: 'Telefon',
  address: 'Adres',
  notes: 'Notatki',
  adults: 'Dorośli',
  children: 'Dzieci',
  toddlers: 'Maluszki',
  guests: 'Goście łącznie',
  hall: 'Sala',
  hallId: 'Sala',
  hallName: 'Nazwa sali',
  client: 'Klient',
  clientId: 'Klient',
  eventType: 'Typ wydarzenia',
  eventTypeId: 'Typ wydarzenia',
  eventTypeName: 'Nazwa wydarzenia',
  startDateTime: 'Data rozpoczęcia',
  endDateTime: 'Data zakończenia',
  date: 'Data',
  totalPrice: 'Cena całkowita',
  pricePerAdult: 'Cena za dorosłego',
  pricePerChild: 'Cena za dziecko',
  pricePerToddler: 'Cena za maluszka',
  discountType: 'Typ rabatu',
  discountValue: 'Wartość rabatu',
  discountAmount: 'Kwota rabatu',
  discountReason: 'Powód rabatu',
  priceBeforeDiscount: 'Cena przed rabatem',
  confirmationDeadline: 'Termin potwierdzenia',
  customEventType: 'Własny typ wydarzenia',
  birthdayAge: 'Wiek urodzinowy',
  anniversaryYear: 'Rok rocznicy',
  anniversaryOccasion: 'Okazja rocznicy',
  archivedAt: 'Data archiwizacji',
  archiveReason: 'Powód archiwizacji',
  name: 'Nazwa',
  capacity: 'Pojemność',
  description: 'Opis',
  amount: 'Kwota',
  paidAt: 'Data płatności',
  method: 'Metoda płatności',
  reason: 'Powód',
  createdAt: 'Data utworzenia',
  updatedAt: 'Data aktualizacji',
}

// Pola do ukrycia — zbyt techniczne / nieczytelne dla użytkownika
export const HIDDEN_FIELDS = new Set([
  'menuSnapshot',
  'createdBy',
  'updatedBy',
  'deletedAt',
  'deletedBy',
  'id',
  'reservationId',
  'clientId',
  'hallId',
  'eventTypeId',
  'userId',
  'menuSelections',
  'menuPackageId',
  'menuTemplateId',
])
