/**
 * Centralized Error Code Enum
 *
 * Kategorie:
 * - VALIDATION_*  (400) — nieprawidłowe dane wejściowe
 * - NOT_FOUND_*   (404) — zasób nie znaleziony
 * - CONFLICT_*    (409) — duplikaty, nieprawidłowy stan
 * - FORBIDDEN_*   (403) — brak uprawnień
 * - INTERNAL_*    (500) — nieoczekiwane błędy
 */

// ═══════════════════════════════════════
// ErrorCode enum
// ═══════════════════════════════════════

export enum ErrorCode {
  // ——— VALIDATION (400) ———
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',
  VALIDATION_REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_UUID = 'VALIDATION_INVALID_UUID',
  VALIDATION_INVALID_DATE = 'VALIDATION_INVALID_DATE',
  VALIDATION_INVALID_EMAIL = 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_PHONE = 'VALIDATION_INVALID_PHONE',
  VALIDATION_INVALID_PRICE = 'VALIDATION_INVALID_PRICE',
  VALIDATION_PASSWORD_WEAK = 'VALIDATION_PASSWORD_WEAK',
  VALIDATION_GUESTS_REQUIRED = 'VALIDATION_GUESTS_REQUIRED',
  VALIDATION_DATE_IN_FUTURE = 'VALIDATION_DATE_IN_FUTURE',
  VALIDATION_END_AFTER_START = 'VALIDATION_END_AFTER_START',
  VALIDATION_INVALID_JSON = 'VALIDATION_INVALID_JSON',
  VALIDATION_DISCOUNT_EXCEEDS = 'VALIDATION_DISCOUNT_EXCEEDS',
  VALIDATION_MENU_DATA = 'VALIDATION_MENU_DATA',

  // ——— NOT_FOUND (404) ———
  NOT_FOUND_RESERVATION = 'NOT_FOUND_RESERVATION',
  NOT_FOUND_CLIENT = 'NOT_FOUND_CLIENT',
  NOT_FOUND_HALL = 'NOT_FOUND_HALL',
  NOT_FOUND_USER = 'NOT_FOUND_USER',
  NOT_FOUND_EVENT_TYPE = 'NOT_FOUND_EVENT_TYPE',
  NOT_FOUND_DEPOSIT = 'NOT_FOUND_DEPOSIT',
  NOT_FOUND_MENU_TEMPLATE = 'NOT_FOUND_MENU_TEMPLATE',
  NOT_FOUND_MENU_PACKAGE = 'NOT_FOUND_MENU_PACKAGE',
  NOT_FOUND_MENU_OPTION = 'NOT_FOUND_MENU_OPTION',
  NOT_FOUND_MENU_COURSE = 'NOT_FOUND_MENU_COURSE',
  NOT_FOUND_DISH = 'NOT_FOUND_DISH',
  NOT_FOUND_ROLE = 'NOT_FOUND_ROLE',
  NOT_FOUND_ATTACHMENT = 'NOT_FOUND_ATTACHMENT',
  NOT_FOUND_SERVICE_CATEGORY = 'NOT_FOUND_SERVICE_CATEGORY',
  NOT_FOUND_SERVICE_ITEM = 'NOT_FOUND_SERVICE_ITEM',
  NOT_FOUND_RECORD = 'NOT_FOUND_RECORD',
  NOT_FOUND_RESOURCE = 'NOT_FOUND_RESOURCE',

  // ——— CONFLICT (409) ———
  CONFLICT_DUPLICATE = 'CONFLICT_DUPLICATE',
  CONFLICT_EMAIL_EXISTS = 'CONFLICT_EMAIL_EXISTS',
  CONFLICT_SLUG_EXISTS = 'CONFLICT_SLUG_EXISTS',
  CONFLICT_NIP_EXISTS = 'CONFLICT_NIP_EXISTS',
  CONFLICT_TIME_SLOT_BOOKED = 'CONFLICT_TIME_SLOT_BOOKED',
  CONFLICT_ALREADY_CANCELLED = 'CONFLICT_ALREADY_CANCELLED',
  CONFLICT_ALREADY_ARCHIVED = 'CONFLICT_ALREADY_ARCHIVED',
  CONFLICT_ALREADY_PAID = 'CONFLICT_ALREADY_PAID',
  CONFLICT_STATUS_TRANSITION = 'CONFLICT_STATUS_TRANSITION',
  CONFLICT_CANNOT_DELETE_IN_USE = 'CONFLICT_CANNOT_DELETE_IN_USE',
  CONFLICT_CAPACITY_EXCEEDED = 'CONFLICT_CAPACITY_EXCEEDED',
  CONFLICT_CONCURRENT_MODIFICATION = 'CONFLICT_CONCURRENT_MODIFICATION',

  // ——— FORBIDDEN (403) ———
  FORBIDDEN_ACCESS_DENIED = 'FORBIDDEN_ACCESS_DENIED',
  FORBIDDEN_INSUFFICIENT_PERMISSIONS = 'FORBIDDEN_INSUFFICIENT_PERMISSIONS',
  FORBIDDEN_ACCOUNT_INACTIVE = 'FORBIDDEN_ACCOUNT_INACTIVE',
  FORBIDDEN_CANNOT_MODIFY_SELF = 'FORBIDDEN_CANNOT_MODIFY_SELF',
  FORBIDDEN_PROTECTED_RESOURCE = 'FORBIDDEN_PROTECTED_RESOURCE',

  // ——— AUTH (401) ———
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',

  // ——— INTERNAL (500) ———
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INTERNAL_DATABASE_ERROR = 'INTERNAL_DATABASE_ERROR',
  INTERNAL_EMAIL_SEND_FAILED = 'INTERNAL_EMAIL_SEND_FAILED',
  INTERNAL_FILE_UPLOAD_FAILED = 'INTERNAL_FILE_UPLOAD_FAILED',
  INTERNAL_PDF_GENERATION_FAILED = 'INTERNAL_PDF_GENERATION_FAILED',
  INTERNAL_EXPORT_FAILED = 'INTERNAL_EXPORT_FAILED',
}

// ═══════════════════════════════════════
// ErrorCode → HTTP status code mapping
// ═══════════════════════════════════════

const ERROR_CODE_STATUS: Record<ErrorCode, number> = {
  // VALIDATION → 400
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.VALIDATION_INVALID_FORMAT]: 400,
  [ErrorCode.VALIDATION_REQUIRED_FIELD]: 400,
  [ErrorCode.VALIDATION_INVALID_UUID]: 400,
  [ErrorCode.VALIDATION_INVALID_DATE]: 400,
  [ErrorCode.VALIDATION_INVALID_EMAIL]: 400,
  [ErrorCode.VALIDATION_INVALID_PHONE]: 400,
  [ErrorCode.VALIDATION_INVALID_PRICE]: 400,
  [ErrorCode.VALIDATION_PASSWORD_WEAK]: 422,
  [ErrorCode.VALIDATION_GUESTS_REQUIRED]: 400,
  [ErrorCode.VALIDATION_DATE_IN_FUTURE]: 400,
  [ErrorCode.VALIDATION_END_AFTER_START]: 400,
  [ErrorCode.VALIDATION_INVALID_JSON]: 400,
  [ErrorCode.VALIDATION_DISCOUNT_EXCEEDS]: 400,
  [ErrorCode.VALIDATION_MENU_DATA]: 400,

  // NOT_FOUND → 404
  [ErrorCode.NOT_FOUND_RESERVATION]: 404,
  [ErrorCode.NOT_FOUND_CLIENT]: 404,
  [ErrorCode.NOT_FOUND_HALL]: 404,
  [ErrorCode.NOT_FOUND_USER]: 404,
  [ErrorCode.NOT_FOUND_EVENT_TYPE]: 404,
  [ErrorCode.NOT_FOUND_DEPOSIT]: 404,
  [ErrorCode.NOT_FOUND_MENU_TEMPLATE]: 404,
  [ErrorCode.NOT_FOUND_MENU_PACKAGE]: 404,
  [ErrorCode.NOT_FOUND_MENU_OPTION]: 404,
  [ErrorCode.NOT_FOUND_MENU_COURSE]: 404,
  [ErrorCode.NOT_FOUND_DISH]: 404,
  [ErrorCode.NOT_FOUND_ROLE]: 404,
  [ErrorCode.NOT_FOUND_ATTACHMENT]: 404,
  [ErrorCode.NOT_FOUND_SERVICE_CATEGORY]: 404,
  [ErrorCode.NOT_FOUND_SERVICE_ITEM]: 404,
  [ErrorCode.NOT_FOUND_RECORD]: 404,
  [ErrorCode.NOT_FOUND_RESOURCE]: 404,

  // CONFLICT → 409
  [ErrorCode.CONFLICT_DUPLICATE]: 409,
  [ErrorCode.CONFLICT_EMAIL_EXISTS]: 409,
  [ErrorCode.CONFLICT_SLUG_EXISTS]: 409,
  [ErrorCode.CONFLICT_NIP_EXISTS]: 409,
  [ErrorCode.CONFLICT_TIME_SLOT_BOOKED]: 409,
  [ErrorCode.CONFLICT_ALREADY_CANCELLED]: 409,
  [ErrorCode.CONFLICT_ALREADY_ARCHIVED]: 409,
  [ErrorCode.CONFLICT_ALREADY_PAID]: 409,
  [ErrorCode.CONFLICT_STATUS_TRANSITION]: 409,
  [ErrorCode.CONFLICT_CANNOT_DELETE_IN_USE]: 409,
  [ErrorCode.CONFLICT_CAPACITY_EXCEEDED]: 409,
  [ErrorCode.CONFLICT_CONCURRENT_MODIFICATION]: 409,

  // FORBIDDEN → 403
  [ErrorCode.FORBIDDEN_ACCESS_DENIED]: 403,
  [ErrorCode.FORBIDDEN_INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.FORBIDDEN_ACCOUNT_INACTIVE]: 403,
  [ErrorCode.FORBIDDEN_CANNOT_MODIFY_SELF]: 403,
  [ErrorCode.FORBIDDEN_PROTECTED_RESOURCE]: 403,

  // AUTH → 401
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_REQUIRED]: 401,
  [ErrorCode.AUTH_SESSION_EXPIRED]: 401,

  // INTERNAL → 500
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.INTERNAL_DATABASE_ERROR]: 500,
  [ErrorCode.INTERNAL_EMAIL_SEND_FAILED]: 500,
  [ErrorCode.INTERNAL_FILE_UPLOAD_FAILED]: 500,
  [ErrorCode.INTERNAL_PDF_GENERATION_FAILED]: 500,
  [ErrorCode.INTERNAL_EXPORT_FAILED]: 500,
};

/**
 * Get HTTP status code for a given ErrorCode.
 */
export function getStatusForErrorCode(code: ErrorCode): number {
  return ERROR_CODE_STATUS[code];
}
